version: "2.4"
services:

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - 3306:3306
    # volumes:
    #   - ~/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: prestogateway
      MYSQL_ROOT_HOST: '%'
  
  presto-gateway:
    build: .
    image: presto-gateway
    container_name: presto-gateway
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - 8082:8080
      - 8095:8090
      - 8096:8091
    environment:
      JDBC_URL: jdbc:mysql://mysqldb:3306/prestogateway
      DB_USER: root
      DB_PASS: root123
      DB_HOST: mysqldb
      DB_NAME: prestogateway
      DB_PORT: 3306
    volumes:
      - ./config/gateway-ha-config.yml.template:/var/lib/presto-gateway/config/gateway-ha-config.yml.template
      - ./config/rules.yml:/var/lib/presto-gateway/config/rules.yml
      