routingRules:
  rulesEngineEnabled: False
  # rulesConfigPath: "src/main/resources/rules/routing_rules.yml"

requestRouter:
  port: 8080
  name: prestoRouter
  historySize: 1000

initialBackends:
  backends:
    - name: adhoc
      proxyTo: http://192.168.1.4:8085

externalPresto:
  jdbcUrl:  jdbc:trino://192.168.1.4:8085
  user: external-presto
  enabled: true

dataStore:
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/prestogateway
  user: root
  password: root123
  driver: com.mysql.cj.jdbc.Driver


server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

notifier:
  smtpHost: localhost
  smtpPort: 587
  sender: presto-gw-monitor-noreply@lyft.com
  recipients:
    - prestodev@yourorg.com

modules:
  - com.lyft.data.gateway.ha.module.HaGatewayProviderModuleWithCardIdRouting

managedApps:
  - com.lyft.data.gateway.ha.GatewayManagedApp

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.lyft: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /tmp/prestoproxy-java.log
      archivedLogFilenamePattern: /tmp/prestoproxy/prestoproxy-java-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB